### PR TITLE
Finishing Deck class

### PR DESCRIPTION
**Pull request by incomingstick**
This pull request should contain a fully functioning deck class by the time I merge. This may sit in queue for a few days.

### CODE REVIEW

**Comment by EricFalkenberg** [comment]
Can you explain lines 118 and 123 in deck.cpp to me?
I noticed that the compiler throws two warnings in regards to those lines and I'm thinking
they won't work as intended.

The programming practice I've been taught is to treat all warnings as errors.

**Comment by b8horpet** [comment]
It checks the array buffer+offset pointer instead of the content, it is a bug.

&deck[i] == &deck[0]+i -> type of &deck[i] is Card**

**Comment by incomingstick** [comment]
Updated to reflect that change.

**Comment by incomingstick** [comment]
I need more time. The deck class is taking longer than expected. Closing this for now.

**Pull request closed without merging**
